# Generated by Django 4.2.2 on 2023-09-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
